# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centralserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x65ntralserver.proto\"-\n\nServerInfo\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"*\n\x10RegisterResponse\x12\x16\n\x0eprocessed_keys\x18\x01 \x01(\x05\"\x1d\n\x0eMappingRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"$\n\x0fMappingResponse\x12\x11\n\tserver_id\x18\x01 \x01(\t\"\x12\n\x10TerminateRequest\"-\n\x13TerminationResponse\x12\x16\n\x0eprocessed_keys\x18\x01 \x01(\x05\x32\x9c\x01\n\x0f\x43\x65ntralRegistry\x12*\n\x08Register\x12\x0b.ServerInfo\x1a\x11.RegisterResponse\x12\'\n\x06MapKey\x12\x0b.KeyRequest\x1a\x10.MappingResponse\x12\x34\n\tTerminate\x12\x11.TerminateRequest\x1a\x14.TerminationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERINFO']._serialized_start=23
  _globals['_SERVERINFO']._serialized_end=68
  _globals['_KEYREQUEST']._serialized_start=70
  _globals['_KEYREQUEST']._serialized_end=95
  _globals['_REGISTERRESPONSE']._serialized_start=97
  _globals['_REGISTERRESPONSE']._serialized_end=139
  _globals['_MAPPINGREQUEST']._serialized_start=141
  _globals['_MAPPINGREQUEST']._serialized_end=170
  _globals['_MAPPINGRESPONSE']._serialized_start=172
  _globals['_MAPPINGRESPONSE']._serialized_end=208
  _globals['_TERMINATEREQUEST']._serialized_start=210
  _globals['_TERMINATEREQUEST']._serialized_end=228
  _globals['_TERMINATIONRESPONSE']._serialized_start=230
  _globals['_TERMINATIONRESPONSE']._serialized_end=275
  _globals['_CENTRALREGISTRY']._serialized_start=278
  _globals['_CENTRALREGISTRY']._serialized_end=434
# @@protoc_insertion_point(module_scope)
