# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import peerserver_pb2 as peerserver__pb2


class PeerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insercao = channel.unary_unary(
                '/peer.PeerServer/Insercao',
                request_serializer=peerserver__pb2.InsertRequest.SerializeToString,
                response_deserializer=peerserver__pb2.InsertResponse.FromString,
                )
        self.Consulta = channel.unary_unary(
                '/peer.PeerServer/Consulta',
                request_serializer=peerserver__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=peerserver__pb2.ConsultaResponse.FromString,
                )
        self.Ativacao = channel.unary_unary(
                '/peer.PeerServer/Ativacao',
                request_serializer=peerserver__pb2.AtivacaoRequest.SerializeToString,
                response_deserializer=peerserver__pb2.AtivacaoResponse.FromString,
                )
        self.Termino = channel.unary_unary(
                '/peer.PeerServer/Termino',
                request_serializer=peerserver__pb2.TerminoRequest.SerializeToString,
                response_deserializer=peerserver__pb2.TerminoResponse.FromString,
                )


class PeerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insercao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ativacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Termino(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insercao': grpc.unary_unary_rpc_method_handler(
                    servicer.Insercao,
                    request_deserializer=peerserver__pb2.InsertRequest.FromString,
                    response_serializer=peerserver__pb2.InsertResponse.SerializeToString,
            ),
            'Consulta': grpc.unary_unary_rpc_method_handler(
                    servicer.Consulta,
                    request_deserializer=peerserver__pb2.ConsultaRequest.FromString,
                    response_serializer=peerserver__pb2.ConsultaResponse.SerializeToString,
            ),
            'Ativacao': grpc.unary_unary_rpc_method_handler(
                    servicer.Ativacao,
                    request_deserializer=peerserver__pb2.AtivacaoRequest.FromString,
                    response_serializer=peerserver__pb2.AtivacaoResponse.SerializeToString,
            ),
            'Termino': grpc.unary_unary_rpc_method_handler(
                    servicer.Termino,
                    request_deserializer=peerserver__pb2.TerminoRequest.FromString,
                    response_serializer=peerserver__pb2.TerminoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peer.PeerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PeerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insercao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peer.PeerServer/Insercao',
            peerserver__pb2.InsertRequest.SerializeToString,
            peerserver__pb2.InsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Consulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peer.PeerServer/Consulta',
            peerserver__pb2.ConsultaRequest.SerializeToString,
            peerserver__pb2.ConsultaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ativacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peer.PeerServer/Ativacao',
            peerserver__pb2.AtivacaoRequest.SerializeToString,
            peerserver__pb2.AtivacaoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Termino(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/peer.PeerServer/Termino',
            peerserver__pb2.TerminoRequest.SerializeToString,
            peerserver__pb2.TerminoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
